# site name
prefixName: さくら荘その
siteName: 泉此方
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/qcf_head.jpg
url: https://github.com/izumikonata10
description: 泉此方的个人博客！
cdn: https://cdn.jsdelivr.net/gh/izumikonata10/cdn/sakura
pjax: 1
# 1开启
mathjax: 0
# 网站公告
notice: 这里是网站公告！但是因为还没有建成，所以没有公告...
lazyloadImg: https://cdn.jsdelivr.net/gh/izumikonata10/cdn/sakura/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    #随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    #图集: {path: /tags/图集/, fa: fa-photo },
    游戏: {path: /tags/游戏/, fa: fa-cloud-download }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  #赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  #客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/izumikonata10/cdn/sakura/img/cover/Gilgamesh1.png
  - https://cdn.jsdelivr.net/gh/izumikonata10/cdn/sakura/img/cover/aqua1.png
  - https://cdn.jsdelivr.net/gh/izumikonata10/cdn/sakura/img/cover/darksoul3(1).jpg
  - https://cdn.jsdelivr.net/gh/izumikonata10/cdn/sakura/img/cover/ketsunomito1.jpg
  - https://cdn.jsdelivr.net/gh/izumikonata10/cdn/sakura/img/cover/MatoiRyuuko1.jpg
  - https://cdn.jsdelivr.net/gh/izumikonata10/cdn/sakura/img/cover/meme1.jpg
  - https://cdn.jsdelivr.net/gh/izumikonata10/cdn/sakura/img/cover/rwby1.png
  - https://cdn.jsdelivr.net/gh/izumikonata10/cdn/sakura/img/cover/rayxzake1.png

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
# bgclass: filter-dot
bgclass: 

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/6516529, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 09/14/2021

# 社交按钮social  url, img PC端配置
social:
  github: {url: http://github.com/izumikonata10, img: /img/social/github.png}
  sina: {url: /#, img: /img/social/sina.png}
  wangyiyun: {url:  http://music.163.com/m/user/home?id=314605619, img: /img/social/wangyiyun.png}
  zhihu: {url: /#, img: /img/social/zhihu.png}
  email: {url: /#, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  # wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

# 社交按钮social  url, img 移动端配置
msocial:
  github: {url: http://github.com/izumikonata10, fa: fa-github, color: 333}
  weibo: {url: /#, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=2444639628&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

# 赞赏二维码（其中wechatSQ是赞赏单页面的赞赏码图片）【改】
donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 首页视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/izumikonata10/cdn/sakura/video
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用 【改】
  name: Unbroken.mp4

# 左下角aplayer播放器配置 主要改id和server这两项，修改详见[aplayer文档] 【改】
aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# 评论,你需要在leancloud注册账号：https://www.leancloud.cn/ 然后获取id和秘钥
# Valine
valine: true
v_appId: JXvtt44DrXza7y1yfMxve3T5-gzGzoHsz
v_appKey: ntTNwuATC8AClW1mHym1283K

